import "./index.css";
export default function App() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AssessmentResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Load last assessment on mount
  React.useEffect(() => {
    const saved = localStorage.getItem("last_assessment");
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        // We don't auto-load it into the UI immediately to avoid confusion, 
        // but we'll show a button if it exists.
      } catch (e) {
        localStorage.removeItem("last_assessment");
      }
    }
  }, []);

  const loadLastAssessment = () => {
    const saved = localStorage.getItem("last_assessment");
    if (saved) {
      setResult(JSON.parse(saved));
    }
  };

  const handleAssess = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!url) return;
    
    setLoading(true);
    setError(null);
    try {
      const repoData = await fetchRepoData(url);
      const assessment = await assessRepository(repoData);
      setResult(assessment);
      localStorage.setItem("last_assessment", JSON.stringify(assessment));
    } catch (err: any) {
      setError(err.message || "Failed to assess repository. Please check the URL and try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadJson = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `assessment-${result.score}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadHtml = () => {
    if (!result) return;
    
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RepoReady Assessment Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #141414; background: #E4E3E0; padding: 40px; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border: 1px solid #141414; }
        h1 { text-transform: uppercase; letter-spacing: -0.02em; border-bottom: 2px solid #141414; padding-bottom: 10px; }
        .score-box { font-size: 48px; font-weight: bold; margin: 20px 0; }
        .summary { font-style: italic; margin-bottom: 30px; color: #444; }
        .check-item { border-bottom: 1px solid #eee; padding: 15px 0; }
        .check-header { display: flex; justify-content: space-between; font-weight: bold; }
        .status-passed { color: #059669; }
        .status-failed { color: #dc2626; }
        .rationale { font-size: 14px; color: #666; margin-top: 5px; }
        .fix-list { background: #f9f9f9; padding: 20px; border: 1px dashed #141414; margin-top: 30px; }
        .fix-item { margin-bottom: 10px; font-size: 14px; }
        .priority-high { color: #dc2626; font-weight: bold; }
    </style>
</head>
<body>
    <div class="container">
        <h1>RepoReady Assessment Report</h1>
        <div class="score-box">Score: ${result.score}/100</div>
        <p class="summary">${result.summary}</p>
        
        <h2>Detailed Assessment</h2>
        ${result.checks.map(check => `
            <div class="check-item">
                <div class="check-header">
                    <span>${check.label}</span>
                    <span class="${check.passed ? 'status-passed' : 'status-failed'}">
                        ${check.passed ? 'PASSED' : 'FAILED'} (${check.score}/${check.maxScore})
                    </span>
                </div>
                <div class="rationale">${check.rationale}</div>
            </div>
        `).join('')}
        
        <div class="fix-list">
            <h2>Priority Fixes</h2>
            ${result.fixChecklist.map(fix => `
                <div class="fix-item">
                    <span class="${fix.impact === 'high' ? 'priority-high' : ''}">[${fix.impact.toUpperCase()}]</span> 
                    ${fix.task}
                </div>
            `).join('')}
        </div>
        
        <p style="margin-top: 40px; font-size: 12px; opacity: 0.5;">Generated by RepoReady on ${new Date().toLocaleDateString()}</p>
    </div>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `assessment-${result.score}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-bg text-ink font-sans selection:bg-accent selection:text-accent-foreground">
      {/* Header */}
      <header className="sticky top-0 z-50 glass border-b border-border/50 px-6 py-4 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="bg-accent p-2 rounded-xl">
            <Shield className="w-6 h-6 text-accent-foreground" />
          </div>
          <h1 className="text-xl font-bold tracking-tight">RepoReady</h1>
        </div>
        <div className="hidden md:flex items-center gap-4">
          <div className="flex items-center gap-2 px-3 py-1 bg-accent/10 rounded-full">
            <div className="w-2 h-2 bg-accent rounded-full animate-pulse" />
            <span className="text-[10px] font-bold text-accent uppercase tracking-wider">Live Assessment</span>
          </div>
          <span className="text-[10px] font-mono uppercase tracking-widest text-muted">v1.0.0</span>
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-6 md:p-12">
        {/* Hero Section */}
        <section className="mb-16 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl mx-auto"
          >
            <h2 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 bg-gradient-to-br from-ink to-muted bg-clip-text text-transparent">
              Is your software research-ready?
            </h2>
            <p className="text-lg text-muted mb-10 max-w-xl mx-auto">
              Automatically assess your GitHub repository for readiness with weighted scoring and prioritized fix checklists.
            </p>
            
            <form onSubmit={handleAssess} className="relative max-w-2xl mx-auto">
              <div className="relative group">
                <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none">
                  <Github className="w-5 h-5 text-muted group-focus-within:text-accent transition-colors" />
                </div>
                <input
                  type="text"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://github.com/owner/repo"
                  className="w-full bg-white border border-border rounded-2xl py-5 pl-12 pr-16 text-lg focus:outline-none focus:ring-4 focus:ring-accent/10 focus:border-accent transition-all shadow-sm"
                />
                <button
                  type="submit"
                  disabled={loading}
                  className="absolute right-2 top-1/2 -translate-y-1/2 bg-accent text-accent-foreground p-3 rounded-xl hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:hover:scale-100 shadow-lg shadow-accent/20"
                >
                  {loading ? <Loader2 className="w-6 h-6 animate-spin" /> : <ArrowRight className="w-6 h-6" />}
                </button>
              </div>
              
              {error && (
                <motion.p 
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  className="mt-4 text-red-500 font-medium text-sm flex items-center justify-center gap-2"
                >
                  <AlertCircle className="w-4 h-4" /> {error}
                </motion.p>
              )}
              
              <div className="mt-6 flex flex-wrap justify-center gap-3">
                <span className="text-[10px] font-bold text-muted uppercase tracking-widest">Try these:</span>
                <button type="button" onClick={() => setUrl("github.com/facebook/react")} className="text-[10px] font-mono bg-white border border-border px-3 py-1 rounded-full hover:border-accent hover:text-accent transition-colors">facebook/react</button>
                <button type="button" onClick={() => setUrl("github.com/octocat/Spoon-Knife")} className="text-[10px] font-mono bg-white border border-border px-3 py-1 rounded-full hover:border-accent hover:text-accent transition-colors">octocat/Spoon-Knife</button>
                {localStorage.getItem("last_assessment") && (
                  <button 
                    type="button" 
                    onClick={loadLastAssessment}
                    className="text-[10px] font-bold text-accent bg-accent/5 border border-accent/20 px-3 py-1 rounded-full hover:bg-accent/10 transition-colors flex items-center gap-1"
                  >
                    <ListChecks className="w-3 h-3" /> Load Last Assessment
                  </button>
                )}
              </div>
            </form>
          </motion.div>
        </section>

        <AnimatePresence mode="wait">
          {result && !loading && (
            <motion.div
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              className="grid grid-cols-1 lg:grid-cols-12 gap-8"
            >
              {/* Left Column: Summary & Fixes */}
              <div className="lg:col-span-4 space-y-8">
                {/* Score Card */}
                <div className="bg-white rounded-3xl p-8 card-shadow border border-border/50 relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-accent/5 rounded-full -mr-16 -mt-16 blur-3xl" />
                  
                  <div className="flex justify-between items-start mb-8">
                    <div>
                      <span className="text-[10px] font-bold text-muted uppercase tracking-widest block mb-1">Overall Score</span>
                      <h3 className="text-sm font-bold">Research Readiness</h3>
                    </div>
                    <div className="bg-accent/10 p-2 rounded-lg">
                      <Trophy className="w-5 h-5 text-accent" />
                    </div>
                  </div>

                  <div className="flex items-baseline gap-2 mb-6">
                    <span className="text-8xl font-black tracking-tighter text-ink">{result.score}</span>
                    <span className="text-xl font-bold text-muted">/100</span>
                  </div>

                  <div className="w-full bg-border/30 h-2 rounded-full mb-8 overflow-hidden">
                    <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: `${result.score}%` }}
                      transition={{ duration: 1, ease: "easeOut" }}
                      className={cn(
                        "h-full rounded-full",
                        result.score > 80 ? "bg-emerald-500" : result.score > 50 ? "bg-amber-500" : "bg-red-500"
                      )}
                    />
                  </div>

                  <p className="text-sm text-muted leading-relaxed mb-8">{result.summary}</p>
                  
                  <div className="grid grid-cols-2 gap-3">
                    <button 
                      onClick={downloadJson}
                      className="flex items-center justify-center gap-2 bg-white border border-border py-3 rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-bg transition-colors"
                    >
                      <Download className="w-3 h-3" /> JSON
                    </button>
                    <button 
                      onClick={downloadHtml}
                      className="flex items-center justify-center gap-2 bg-ink text-white py-3 rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-ink/90 transition-colors shadow-lg shadow-ink/20"
                    >
                      <FileText className="w-3 h-3" /> HTML Report
                    </button>
                  </div>
                </div>

                {/* Fix Checklist */}
                <div className="bg-ink rounded-3xl p-8 text-white shadow-2xl shadow-ink/20">
                  <div className="flex items-center gap-3 mb-8">
                    <div className="bg-white/10 p-2 rounded-lg">
                      <ListChecks className="w-5 h-5 text-white" />
                    </div>
                    <h3 className="text-[10px] font-bold uppercase tracking-widest">Priority Fix Checklist</h3>
                  </div>
                  
                  <div className="space-y-6">
                    {result.fixChecklist.length === 0 ? (
                      <div className="text-sm text-white/50 italic py-4">No fixes needed! Repository is research-ready.</div>
                    ) : (
                      result.fixChecklist.sort((a, b) => b.priority - a.priority).map((fix, i) => (
                        <motion.div 
                          key={i}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.1 }}
                          className="group border-b border-white/10 pb-6 last:border-0"
                        >
                          <div className="flex justify-between items-start mb-2">
                            <span className="text-sm font-medium leading-tight">{fix.task}</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <span className={cn(
                              "text-[8px] font-bold uppercase px-2 py-0.5 rounded-full border",
                              fix.impact === "high" ? "border-red-500 text-red-400 bg-red-500/10" : "border-white/20 text-white/40"
                            )}>
                              {fix.impact} Impact
                            </span>
                          </div>
                        </motion.div>
                      ))
                    )}
                  </div>
                </div>
              </div>

              {/* Right Column: Detailed Checks */}
              <div className="lg:col-span-8">
                <div className="bg-white rounded-3xl border border-border/50 card-shadow overflow-hidden">
                  <div className="p-8 border-b border-border/50 bg-bg/30 flex justify-between items-center">
                    <h3 className="text-sm font-bold uppercase tracking-widest">Detailed Assessment</h3>
                    <div className="text-[10px] font-mono text-muted">{result.checks.length} Checks Performed</div>
                  </div>
                  
                  <div className="divide-y divide-border/50">
                    {result.checks.map((check, i) => (
                      <motion.div 
                        key={check.id} 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ 
                          opacity: 1, 
                          y: 0,
                          scale: check.passed ? [1, 1.01, 1] : 1,
                          x: !check.passed ? [0, -2, 2, -2, 2, 0] : 0
                        }}
                        transition={{ 
                          delay: i * 0.05,
                          scale: check.passed ? { duration: 2, repeat: Infinity, ease: "easeInOut" } : {},
                          x: !check.passed ? { duration: 0.5, repeat: Infinity, repeatDelay: 3 } : {}
                        }}
                        className="p-8 hover:bg-bg/20 transition-colors group flex gap-6"
                      >
                        <div className="flex-shrink-0 pt-1">
                          {check.passed ? (
                            <div className="bg-emerald-100 p-2 rounded-xl">
                              <CheckCircle2 className="w-6 h-6 text-emerald-600" />
                            </div>
                          ) : (
                            <div className="bg-red-100 p-2 rounded-xl">
                              <XCircle className="w-6 h-6 text-red-500" />
                            </div>
                          )}
                        </div>
                        
                        <div className="flex-grow">
                          <div className="flex justify-between items-start mb-2">
                            <h4 className="text-lg font-bold tracking-tight">{check.label}</h4>
                            <div className="text-right">
                              <div className="text-sm font-bold mb-1">
                                {check.score}<span className="text-muted font-normal">/{check.maxScore}</span>
                              </div>
                              <span className={cn(
                                "text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border",
                                check.impact === "high" ? "border-red-200 text-red-600 bg-red-50" : "border-border text-muted"
                              )}>
                                {check.impact} Impact
                              </span>
                            </div>
                          </div>
                          <p className="text-sm text-muted leading-relaxed max-w-2xl">{check.rationale}</p>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Empty State */}
        {!result && !loading && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 0.4 }}
            className="mt-24 flex flex-col items-center text-center"
          >
            <div className="bg-white p-8 rounded-full card-shadow mb-8">
              <Github className="w-16 h-16 text-muted" />
            </div>
            <p className="font-bold text-xs uppercase tracking-[0.3em] text-muted">Enter a public GitHub URL to begin assessment</p>
          </motion.div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="mt-24 flex flex-col items-center text-center">
            <div className="relative w-24 h-24 mb-8">
              <motion.div 
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                className="absolute inset-0 border-4 border-accent border-t-transparent rounded-full"
              />
              <Shield className="absolute inset-0 m-auto w-10 h-10 text-accent animate-pulse" />
            </div>
            <p className="text-2xl font-bold tracking-tight mb-2">Analyzing repository architecture...</p>
            <p className="text-sm text-muted uppercase tracking-widest font-bold">Fetching file tree, README, and release history</p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="max-w-7xl mx-auto p-12 border-t border-border/50 mt-12 flex flex-col md:flex-row justify-between items-center gap-6 opacity-40">
        <div className="flex items-center gap-2">
          <Shield className="w-4 h-4" />
          <span className="text-[10px] font-bold uppercase tracking-widest">RepoReady Assessment Engine</span>
        </div>
        <div className="text-[10px] font-mono">
          &copy; 2026 RESEARCH SOFTWARE READINESS TOOL
        </div>
      </footer>
    </div>
  );
}
